#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1

start_service() {
        mkdir -p /etc/tailscale

        procd_open_instance main

        procd_set_param command /usr/sbin/tailscaled
        procd_append_param command --state /etc/tailscale/tailscaled.state
        procd_append_param command --port 41641

        procd_set_param env TS_DEBUG_FIREWALL_MODE=nftables
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1

        procd_close_instance
}
